#!/usr/bin/env python

import argparse, time, sys, os, subprocess

pyExec = sys.executable
print(pyExec)
if "/" in sys.argv[0]:
    diploShicDir = "/".join(sys.argv[0].split("/")[:-1]) + "/"
else:
    diploShicDir = ""

################# use argparse to get CL args and make sure we are kosher
parser = argparse.ArgumentParser(
    description="calculate feature vectors, train, or predict with diploSHIC"
)
parser._positionals.title = "possible modes (enter 'python diploSHIC.py modeName -h' for modeName's help message"
subparsers = parser.add_subparsers(help="sub-command help")
parser_c = subparsers.add_parser(
    "fvecSim", help="Generate feature vectors from simulated data"
)
parser_e = subparsers.add_parser(
    "makeTrainingSets",
    help="Combine feature vectors from muliple fvecSim runs into 5 balanced training sets",
)
parser_a = subparsers.add_parser("train", help="train and test a shic CNN")
parser_d = subparsers.add_parser(
    "fvecVcf", help="Generate feature vectors from data in a VCF file"
)
parser_b = subparsers.add_parser(
    "predict", help="perform prediction using an already-trained SHIC CNN"
)
# parser_a.add_argument('nDims', metavar='nDims', type=int,
#                   help='dimensionality of the feature vector')
parser_a.add_argument("trainDir", help="path to training set files")
parser_a.add_argument(
    "testDir", help="path to test set files, can be same as trainDir"
)
parser_a.add_argument(
    "outputModel",
    help="file name for output model, will create two files one with structure one with weights",
)
parser_a.add_argument(
    "--epochs",
    type=int,
    help="max epochs for training CNN (default = 100)",
    default=100,
)
parser_a.add_argument(
    "--numSubWins",
    type=int,
    help="number of subwindows that our chromosome is divided into (default = 11)",
    default=11,
)
parser_a.add_argument(
    "--confusionFile",
    help="optional file to which confusion matrix plot will be written (default = None)",
    default=None,
)
parser_a.add_argument(
    "--model",
    choices=["baseline", "daf"],
    default="baseline",
    help="CNN architecture: 'baseline' (original) or 'daf' (with DAF+distance features) (default = baseline)",
)
parser_a.set_defaults(mode="train")
parser_a._positionals.title = "required arguments"

# parser_b.add_argument('nDims', metavar='nDims', type=int,
#                   help='dimensionality of the feature vector')
parser_b.add_argument(
    "modelStructure", help="path to CNN structure .json file"
)
parser_b.add_argument("modelWeights", help="path to CNN weights .h5 file")
parser_b.add_argument("predictFile", help="input file to predict")
parser_b.add_argument("predictFileOutput", help="output file name")
parser_b.add_argument(
    "--numSubWins",
    type=int,
    help="number of subwindows that our chromosome is divided into (default = 11)",
    default=11,
)
parser_b.add_argument(
    "--simData",
    help="Are we using simulated input data wihout coordinates?",
    action="store_true",
)
parser_b.add_argument(
    "--dafPredictFile",
    help="path to DAF feature file (.daf.fvec) for multi-input model prediction",
    default=None,
)
parser_b.set_defaults(mode="predict")
parser_b._positionals.title = "required arguments"

parser_c.add_argument(
    "shicMode",
    help="specifies whether to use original haploid SHIC (use 'haploid') or diploSHIC ('diploid')",
    default="diploid",
)
parser_c.add_argument(
    "msOutFile",
    help="path to simulation output file (must be same format used by Hudson's ms)",
)
parser_c.add_argument(
    "fvecFileName", help="path to file where feature vectors will be written"
)
parser_c.add_argument(
    "--totalPhysLen",
    type=int,
    help="Length of simulated chromosome for converting infinite sites ms output to finite sites (default=1100000)",
    default=1100000,
)
parser_c.add_argument(
    "--numSubWins",
    type=int,
    help="The number of subwindows that our chromosome will be divided into (default=11)",
    default=11,
)
parser_c.add_argument(
    "--maskFileName",
    help=(
        "Path to a fasta-formatted file that contains masking information (marked by 'N'). "
        "If specified, simulations will be masked in a manner mirroring windows drawn from this file."
    ),
    default="None",
)
parser_c.add_argument(
    "--vcfForMaskFileName",
    help=(
        "Path to a VCF file that contains genotype information. This will be used to mask genotypes "
        "in a manner that mirrors how the true data are masked."
    ),
    default=None,
)
parser_c.add_argument(
    "--popForMask",
    help="The label of the population for which we should draw genotype information from the VCF for masking purposes.",
    default=None,
)
parser_c.add_argument(
    "--sampleToPopFileName",
    help=(
        "Path to tab delimited file with population assignments (used for genotype masking); format: "
        "SampleID\tpopID"
    ),
    default="None",
)
parser_c.add_argument(
    "--unmaskedGenoFracCutoff",
    type=float,
    help="Fraction of unmasked genotypes required to retain a site (default=0.75)",
    default=0.75,
)
parser_c.add_argument(
    "--chrArmsForMasking",
    help=(
        "A comma-separated list (no spaces) of chromosome arms from which we want to draw masking "
        "information (or 'all' if we want to use all arms. Ignored if maskFileName is not specified."
    ),
    default="all",
)
parser_c.add_argument(
    "--unmaskedFracCutoff",
    type=float,
    help="Minimum fraction of unmasked sites, if masking simulated data (default=0.25)",
    default=0.25,
)
parser_c.add_argument(
    "--outStatsDir",
    help="Path to a directory where values of each statistic in each subwindow are recorded for each rep",
    default="None",
)
parser_c.add_argument(
    "--ancFileName",
    help=(
        "Path to a fasta-formatted file that contains inferred ancestral states ('N' if unknown)."
        " This is used for masking, as sites that cannot be polarized are masked, and we mimic this in the simulted data."
        " Ignored in diploid mode which currently does not use ancestral state information"
    ),
    default="None",
)
parser_c.add_argument(
    "--pMisPol",
    type=float,
    help="The fraction of sites that will be intentionally polarized to better approximate real data (default=0.0)",
    default=0.0,
)
parser_c.set_defaults(mode="fvecSim")
parser_c._positionals.title = "required arguments"

parser_d.add_argument(
    "shicMode",
    help="specifies whether to use original haploid SHIC (use 'haploid') or diploSHIC ('diploid')",
)
parser_d.add_argument(
    "chrArmVcfFile",
    help="VCF format file containing data for our chromosome arm (other arms will be ignored)",
)
parser_d.add_argument(
    "chrArm",
    help="Exact name of the chromosome arm for which feature vectors will be calculated",
)
parser_d.add_argument("chrLen", type=int, help="Length of the chromosome arm")
parser_d.add_argument(
    "fvecFileName", help="path to file where feature vectors will be written"
)
parser_d.add_argument(
    "--targetPop",
    help="Population ID of samples we wish to include",
    default="None",
)
parser_d.add_argument(
    "--sampleToPopFileName",
    help=(
        "Path to tab delimited file with population assignments; format: "
        "SampleID\tpopID"
    ),
    default="None",
)
parser_d.add_argument(
    "--winSize",
    type=int,
    help="Length of the large window (default=1100000)",
    default=1100000,
)
parser_d.add_argument(
    "--numSubWins",
    type=int,
    help="Number of sub-windows within each large window (default=11)",
    default=11,
)
parser_d.add_argument(
    "--maskFileName",
    help=(
        "Path to a fasta-formatted file that contains masking information (marked by 'N'); "
        "must have an entry with title matching chrArm"
    ),
    default="None",
)
parser_d.add_argument(
    "--unmaskedFracCutoff",
    type=float,
    help="Fraction of unmasked sites required to retain a subwindow (default=0.25)",
    default=0.25,
)
parser_d.add_argument(
    "--unmaskedGenoFracCutoff",
    type=float,
    help="Fraction of unmasked genotypes required to retain a site (default=0.75)",
    default=0.75,
)
parser_d.add_argument(
    "--ancFileName",
    help=(
        "Path to a fasta-formatted file that contains inferred ancestral states ('N' if unknown); "
        "must have an entry with title matching chrArm. Ignored for diploid mode which currently does not use ancestral "
        "state information."
    ),
    default="None",
)
parser_d.add_argument(
    "--statFileName",
    help="Path to a file where statistics will be written for each subwindow that is not filtered out",
    default="None",
)
parser_d.add_argument(
    "--segmentStart",
    help="Left boundary of region in which feature vectors are calculated (whole arm if omitted)",
    default="None",
)
parser_d.add_argument(
    "--segmentEnd",
    help="Right boundary of region in which feature vectors are calculated (whole arm if omitted)",
    default="None",
)
parser_d.set_defaults(mode="fvecVcf")
parser_d._positionals.title = "required arguments"

parser_e.add_argument(
    "neutTrainingFileName", help="Path to our neutral feature vectors"
)
parser_e.add_argument(
    "softTrainingFilePrefix",
    help=(
        "Prefix (including higher-level path) of files containing soft training examples"
        "; files must end with '_$i.$ext' where $i is the subwindow index of the sweep and $ext is any extension."
    ),
)
parser_e.add_argument(
    "hardTrainingFilePrefix",
    help=(
        "Prefix (including higher-level path) of files containing hard training examples"
        "; files must end with '_$i.$ext' where $i is the subwindow index of the sweep and $ext is any extension."
    ),
)
parser_e.add_argument(
    "sweepTrainingWindows",
    type=int,
    help=(
        "comma-separated list of windows to classify as sweeps (usually just '5'"
        " but without the quotes)"
    ),
)
parser_e.add_argument(
    "linkedTrainingWindows",
    help=(
        "list of windows to treat as linked to sweeps (usually '0,1,2,3,4,6,7,8,9,10' but"
        " without the quotes)"
    ),
)
parser_e.add_argument(
    "outDir", help="path to directory where the training sets will be written"
)
parser_e.set_defaults(mode="makeTrainingSets")
parser_e._positionals.title = "required arguments"
if len(sys.argv) == 1:
    parser.print_help()
    sys.exit(1)
args = parser.parse_args()
argsDict = vars(args)

if argsDict["mode"] in ["train", "predict"]:
    ###########################################################
    # Import a bunch of libraries if everything checks out
    import matplotlib

    matplotlib.use("Agg")
    import json
    import numpy as np
    import tensorflow as tf
    from keras.models import Sequential, Model
    from keras import optimizers
    from keras.layers import Dense, Dropout, Activation, Flatten, Input
    from keras.layers import Conv2D, MaxPooling2D, concatenate
    from sklearn.model_selection import train_test_split
    from tensorflow.keras.preprocessing.image import ImageDataGenerator
    from keras.callbacks import EarlyStopping, ModelCheckpoint
    import keras.backend as K
    import fnmatch
    from diploshic.models import build_baseline_model, build_daf_model

    # nDims = argsDict['nDims']
    numSubWins = argsDict["numSubWins"]
    N_DAF_BINS = 20
    N_DIST_FEATURES = 10  # 4 distance + 3 RAiSD + 3 scan stats

if argsDict["mode"] == "train":
    trainingDir = argsDict["trainDir"]
    testingDir = argsDict["testDir"]
    epochOption = argsDict["epochs"]
    outputModel = argsDict["outputModel"]
    confusionFile = argsDict["confusionFile"]
    modelType = argsDict["model"]

    def loadFvecDir(dataDir):
        """Load all 5 class .fvec files from a directory."""
        classes = ["hard", "neut", "soft", "linkedSoft", "linkedHard"]
        arrays = []
        labels = []
        for ci, cls in enumerate(classes):
            data = np.loadtxt(dataDir + cls + ".fvec", skiprows=1)
            nDims = int(data.shape[1] / numSubWins)
            data = data.reshape(data.shape[0], nDims, numSubWins, 1)
            arrays.append(data)
            labels.append(np.full(data.shape[0], ci))
        return np.concatenate(arrays), np.concatenate(labels), nDims

    def loadDafFvecDir(dataDir):
        """Load all 5 class .daf.fvec files, split into DAF and distance arrays."""
        classes = ["hard", "neut", "soft", "linkedSoft", "linkedHard"]
        dafArrays, distArrays = [], []
        nDafCols = N_DAF_BINS * numSubWins
        for cls in classes:
            data = np.loadtxt(dataDir + cls + ".daf.fvec", skiprows=1)
            dafArrays.append(data[:, :nDafCols].reshape(data.shape[0], N_DAF_BINS, numSubWins, 1))
            distArrays.append(data[:, nDafCols:].reshape(data.shape[0], N_DIST_FEATURES, numSubWins, 1))
        return np.concatenate(dafArrays), np.concatenate(distArrays)

    print("loading data now...")
    X_train, y_train, nDims = loadFvecDir(trainingDir)

    if trainingDir == testingDir:
        X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size=0.2)
    else:
        X_test, y_test, _ = loadFvecDir(testingDir)

    # Load DAF data if using DAF model
    if modelType == "daf":
        print("loading DAF features...")
        daf_train, dist_train = loadDafFvecDir(trainingDir)
        if trainingDir == testingDir:
            # Use same split indices — re-split with same random state not trivial,
            # so just do a fresh split with the same sizes
            n_test = X_test.shape[0]
            n_total = daf_train.shape[0]
            daf_train, daf_test = daf_train[:n_total - n_test], daf_train[n_total - n_test:]
            dist_train, dist_test = dist_train[:n_total - n_test], dist_train[n_total - n_test:]
        else:
            daf_test, dist_test = loadDafFvecDir(testingDir)

    Y_train = tf.keras.utils.to_categorical(y_train, 5)
    Y_test = tf.keras.utils.to_categorical(y_test, 5)
    X_valid, X_test, Y_valid, Y_test = train_test_split(X_test, Y_test, test_size=0.5)

    datagen = ImageDataGenerator(
        featurewise_center=True,
        featurewise_std_normalization=True,
        horizontal_flip=True,
    )
    validation_gen = ImageDataGenerator(
        featurewise_center=True,
        featurewise_std_normalization=True,
        horizontal_flip=False,
    )
    test_gen = ImageDataGenerator(
        featurewise_center=True,
        featurewise_std_normalization=True,
        horizontal_flip=False,
    )

    print("training set has %d examples" % X_train.shape[0])
    print("validation set has %d examples" % X_valid.shape[0])
    print("test set has %d examples" % X_test.shape[0])

    # Build model from models.py
    if modelType == "baseline":
        model = build_baseline_model(nDims, numSubWins)
    elif modelType == "daf":
        model = build_daf_model(nDims, numSubWins)
        # Split DAF validation/test using same indices
        idx_valid = np.arange(len(Y_valid) + len(Y_test))
        # We need to split daf_test the same way X_test was split
        n_val = X_valid.shape[0]
        daf_valid, daf_test_final = daf_test[:n_val], daf_test[n_val:]
        dist_valid, dist_test_final = dist_test[:n_val], dist_test[n_val:]

    model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

    earlystop = EarlyStopping(
        monitor="val_accuracy", min_delta=0.001, patience=5, verbose=1, mode="auto",
    )
    model_json = model.to_json()
    with open(outputModel + ".json", "w") as json_file:
        json_file.write(model_json)
    modWeightsFilepath = outputModel + ".weights.h5"
    checkpoint = ModelCheckpoint(
        modWeightsFilepath, monitor="val_accuracy", verbose=1,
        save_best_only=True, save_weights_only=True, mode="auto",
    )
    callbacks_list = [earlystop, checkpoint]

    # Save model metadata
    with open(outputModel + ".meta.json", "w") as f:
        json.dump({"model_type": modelType, "nDims": nDims, "numSubWins": numSubWins}, f)

    start = time.time()
    if modelType == "baseline":
        datagen.fit(X_train)
        validation_gen.fit(X_valid)
        test_gen.fit(X_test)
        model.fit(
            datagen.flow(X_train, Y_train, batch_size=32),
            steps_per_epoch=int(len(X_train) / 32),
            epochs=epochOption, verbose=1, callbacks=callbacks_list,
            validation_data=validation_gen.flow(X_valid, Y_valid, batch_size=32),
            validation_steps=int(len(X_valid) / 32),
        )
        score = model.evaluate(
            test_gen.flow(X_test, Y_test, batch_size=32), steps=int(len(Y_test) / 32)
        )
    elif modelType == "daf":
        # Normalize each input independently
        def _norm(train, val, test):
            m, s = train.mean(axis=0), train.std(axis=0)
            s[s == 0] = 1.0
            return (train - m) / s, (val - m) / s, (test - m) / s

        X_train_n, X_valid_n, X_test_n = _norm(X_train, X_valid, X_test)
        daf_train_n, daf_valid_n, daf_test_n = _norm(daf_train, daf_valid, daf_test_final)
        dist_train_n, dist_valid_n, dist_test_n = _norm(dist_train, dist_valid, dist_test_final)

        model.fit(
            [X_train_n, daf_train_n, dist_train_n], Y_train,
            batch_size=32, epochs=epochOption, verbose=1, callbacks=callbacks_list,
            validation_data=([X_valid_n, daf_valid_n, dist_valid_n], Y_valid),
        )
        model.load_weights(modWeightsFilepath)
        score = model.evaluate([X_test_n, daf_test_n, dist_test_n], Y_test, verbose=0)

    sys.stderr.write(
        "total time spent fitting and evaluating: %f secs\n" % (time.time() - start)
    )

    print("evaluation on test set:")
    print("diploSHIC loss: %f" % score[0])
    print("diploSHIC accuracy: %f" % score[1])
    if confusionFile:
        from diploshic.misc import plot_confusion_matrix
        import matplotlib.pyplot as plt

        if modelType == "baseline":
            testData = test_gen.standardize(X_test)
        else:
            testData = [X_test_n, daf_test_n, dist_test_n]
        plot_confusion_matrix(
            model, testData, Y_test,
            labels=[0, 4, 2, 3, 1],
            display_labels=["Hard", "Hard-linked", "Soft", "Soft-linked", "Neutral"],
            cmap=plt.cm.Blues, normalize="true",
        )
        plt.savefig(confusionFile, bbox_inches="tight")

elif argsDict["mode"] == "predict":
    import pandas as pd
    from keras.models import model_from_json

    # Detect model type from metadata file
    metaPath = argsDict["modelStructure"].replace(".json", ".meta.json")
    modelType = "baseline"
    if os.path.exists(metaPath):
        with open(metaPath) as f:
            meta = json.load(f)
        modelType = meta.get("model_type", "baseline")

    # import data from predictFile
    x_df = pd.read_table(argsDict["predictFile"])
    if argsDict["simData"]:
        testX = x_df[list(x_df)[:]].to_numpy()
    else:
        testX = x_df[list(x_df)[4:]].to_numpy()
    nDims = int(testX.shape[1] / numSubWins)
    testX = testX.reshape(testX.shape[0], nDims, numSubWins, 1)

    # import model
    json_file = open(argsDict["modelStructure"], "r")
    loaded_model_json = json_file.read()
    json_file.close()
    model = model_from_json(loaded_model_json)
    model.load_weights(argsDict["modelWeights"])
    print("Loaded model from disk")

    if modelType == "daf":
        # Load DAF features
        dafFile = argsDict["dafPredictFile"]
        if dafFile is None:
            sys.exit("Error: --dafPredictFile is required for DAF model prediction\n")
        daf_df = pd.read_table(dafFile)
        if argsDict["simData"]:
            dafData = daf_df[list(daf_df)[:]].to_numpy()
        else:
            dafData = daf_df[list(daf_df)[4:]].to_numpy()
        nDafCols = N_DAF_BINS * numSubWins
        dafX = dafData[:, :nDafCols].reshape(dafData.shape[0], N_DAF_BINS, numSubWins, 1)
        distX = dafData[:, nDafCols:].reshape(dafData.shape[0], N_DIST_FEATURES, numSubWins, 1)

        # Normalize each input
        def _norm_single(X):
            m, s = X.mean(axis=0), X.std(axis=0)
            s[s == 0] = 1.0
            return (X - m) / s

        preds = model.predict([_norm_single(testX), _norm_single(dafX), _norm_single(distX)])
    else:
        # Baseline model — use ImageDataGenerator normalization
        validation_gen = ImageDataGenerator(
            featurewise_center=True,
            featurewise_std_normalization=True,
            horizontal_flip=False,
        )
        validation_gen.fit(testX)
        preds = model.predict(validation_gen.standardize(testX))

    predictions = np.argmax(preds, axis=1)

    # np.repeat(0,len(h1)),np.repeat(1,len(n1)), np.repeat(2,len(s1)), np.repeat(3,len(ls1)), np.repeat(4,len(lh1)
    classDict = {
        0: "hard",
        1: "neutral",
        2: "soft",
        3: "linkedSoft",
        4: "linkedHard",
    }

    # output the predictions
    outputFile = open(argsDict["predictFileOutput"], "w")
    if argsDict["simData"]:
        outputFile.write(
            "predClass\tprob(neutral)\tprob(likedSoft)\tprob(linkedHard)\tprob(soft)\tprob(hard)\n"
        )
    else:
        outputFile.write(
            "chrom\tclassifiedWinStart\tclassifiedWinEnd\tbigWinRange\tpredClass\tprob(neutral)\tprob(likedSoft)\tprob(linkedHard)\tprob(soft)\tprob(hard)\n"
        )

    for index, row in x_df.iterrows():
        if argsDict["simData"]:
            outputFile.write(
                "{}\t{:f}\t{:f}\t{:f}\t{:f}\t{:f}\n".format(
                    classDict[predictions[index]],
                    preds[index][1],
                    preds[index][3],
                    preds[index][4],
                    preds[index][2],
                    preds[index][0],
                )
            )
        else:
            outputFile.write(
                "{}\t{}\t{}\t{}\t{}\t{:f}\t{:f}\t{:f}\t{:f}\t{:f}\n".format(
                    row["chrom"],
                    row["classifiedWinStart"],
                    row["classifiedWinEnd"],
                    row["bigWinRange"],
                    classDict[predictions[index]],
                    preds[index][1],
                    preds[index][3],
                    preds[index][4],
                    preds[index][2],
                    preds[index][0],
                )
            )
    outputFile.close()
    print("{} predictions complete".format(index + 1))
elif argsDict["mode"] == "fvecSim":
    if argsDict["shicMode"].lower() == "diploid":
        cmdArgs = [
            argsDict["msOutFile"],
            argsDict["totalPhysLen"],
            argsDict["numSubWins"],
            argsDict["maskFileName"],
            argsDict["vcfForMaskFileName"],
            argsDict["popForMask"],
            argsDict["sampleToPopFileName"],
            argsDict["unmaskedGenoFracCutoff"],
            argsDict["chrArmsForMasking"],
            argsDict["unmaskedFracCutoff"],
            argsDict["outStatsDir"],
            argsDict["fvecFileName"],
        ]
        cmd = (
            pyExec
            + " "
            + diploShicDir
            + "makeFeatureVecsForSingleMsDiploid.py "
            + " ".join([str(x) for x in cmdArgs])
        )
    elif argsDict["shicMode"].lower() == "haploid":
        cmdArgs = [
            argsDict["msOutFile"],
            argsDict["totalPhysLen"],
            argsDict["numSubWins"],
            argsDict["maskFileName"],
            argsDict["ancFileName"],
            argsDict["chrArmsForMasking"],
            argsDict["unmaskedFracCutoff"],
            argsDict["pMisPol"],
            argsDict["outStatsDir"],
            argsDict["fvecFileName"],
        ]
        cmd = (
            pyExec
            + " "
            + diploShicDir
            + "makeFeatureVecsForSingleMs_ogSHIC.py "
            + " ".join([str(x) for x in cmdArgs])
        )
    else:
        sys.exit("'shicMode' must be set to either 'diploid' or 'haploid'")
    print(cmd)
    subprocess.call(cmd.split())
elif argsDict["mode"] == "fvecVcf":
    if argsDict["shicMode"].lower() == "diploid":
        cmdArgs = [
            argsDict["chrArmVcfFile"],
            argsDict["chrArm"],
            argsDict["chrLen"],
            argsDict["targetPop"],
            argsDict["winSize"],
            argsDict["numSubWins"],
            argsDict["maskFileName"],
            argsDict["unmaskedFracCutoff"],
            argsDict["unmaskedGenoFracCutoff"],
            argsDict["sampleToPopFileName"],
            argsDict["statFileName"],
            argsDict["fvecFileName"],
        ]
        cmd = (
            pyExec
            + " "
            + diploShicDir
            + "makeFeatureVecsForChrArmFromVcfDiploid.py "
            + " ".join([str(x) for x in cmdArgs])
        )
    elif argsDict["shicMode"].lower() == "haploid":
        cmdArgs = [
            argsDict["chrArmVcfFile"],
            argsDict["chrArm"],
            argsDict["chrLen"],
            argsDict["targetPop"],
            argsDict["winSize"],
            argsDict["numSubWins"],
            argsDict["maskFileName"],
            argsDict["unmaskedFracCutoff"],
            argsDict["sampleToPopFileName"],
            argsDict["ancFileName"],
            argsDict["statFileName"],
            argsDict["fvecFileName"],
        ]
        cmd = (
            pyExec
            + " "
            + diploShicDir
            + "makeFeatureVecsForChrArmFromVcf_ogSHIC.py "
            + " ".join([str(x) for x in cmdArgs])
        )
    else:
        sys.exit("'shicMode' must be set to either 'diploid' or 'haploid'")
    additionalArgs = []
    if argsDict["segmentStart"] != "None":
        additionalArgs += [argsDict["segmentStart"], argsDict["segmentEnd"]]
        cmd += " " + " ".join(additionalArgs)
    # cmd += " > " + argsDict['fvecFileName']
    print(cmd)
    subprocess.call(cmd.split())
elif argsDict["mode"] == "makeTrainingSets":
    cmdArgs = [
        argsDict["neutTrainingFileName"],
        argsDict["softTrainingFilePrefix"],
        argsDict["hardTrainingFilePrefix"],
        argsDict["sweepTrainingWindows"],
        argsDict["linkedTrainingWindows"],
        argsDict["outDir"],
    ]
    cmd = (
        pyExec
        + " "
        + diploShicDir
        + "makeTrainingSets.py "
        + " ".join([str(x) for x in cmdArgs])
    )
    print(cmd)
    subprocess.call(cmd.split())
